trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

variables:
- group: tokens

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    yarn config set ignore-engines true &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Compile, line, test"
    npm i
    npm run deploy -- -p $(MARKETPLACE_TOKEN)
  displayName: Compile, Lint, Test
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Publish"
  displayName: Publish
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))